describe('Viewing the Todo List', function () {
  it('should display todo list when user visits the home page', function () {
    cy.visit('/')
    cy.get('[data-testid="todoList"]')
      .should('exist')
  })
  it('should display todo items in the order they are created', function () {
    cy.visit('/')
    cy.get('[data-testid="addButton"]')
      .click()
    cy.get('[data-testid="newTodoDescription"]')
      .type('Get Milk')
    cy.get('[data-testid="newTodoButton"]')
      .click()
    cy.contains('Get Milk')
      .should('exist')
    cy.get('[data-testid="addButton"]')
      .click()
    cy.get('[data-testid="addButton"]')
      .click()
    cy.get('[data-testid="newTodoDescription"]')
      .type('Get Bread')
    cy.get('[data-testid="newTodoButton"]')
      .click()
    cy.contains('Get Bread')
      .should('exist')
    cy.get('[data-testid="todoList"]')
      .contains('Get Milk')
      .should('exist')
    cy.get('[data-testid="todoList"]')
      .contains('Get Bread')
      .should('exist')
  })
  describe('User has created one or more todo items', function () {
    beforeEach(function () {
      cy.visit('/')
      cy.get('[data-testid="addButton"]')
        .click()
      cy.get('[data-testid="newTodoDescription"]')
        .type('Get Milk')
      cy.get('[data-testid="newTodoButton"]')
        .click()
    })
    it('should display todo items with the correct description', function () {
      cy.contains('Get Milk')
        .should('exist')
      cy.get('[data-testid="todoList"]')
        .contains('Get Milk')
        .should('exist')
    })
    it('should see a checkmark next to the item that have been marked as complete', function () {
      cy.get('[data-testid="todoList"]')
        .contains('Get Milk')
        .should('not.have.class', 'completed')
      cy.get('[data-testid="todoList"]')
        .contains('Get Milk')
        .find('[data-testid="completeButton"]')
        .click()
      cy.get('[data-testid="todoList"]')
        .contains('Get Milk')
        .should('have.class', 'completed')
    })
  })
})

export {}
