spring:
  application:
    name: todo-core
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  security:
    user:
      password: password
